### ISSUE TITLE
typo :)

### ISSUE THREAD

**Issue by bonitoflakez** [Assad69/Assad69#1]
I think you forgot to change the organization name here 

https://github.com/8sp/8sp/blob/b57c5408626034f16ab9501adc495157a025131d/README.md?plain=1#L8

**Comment by 8sp** [comment]
Thanks @Nikk-0x11 :)

**Comment by bonitoflakez** [comment]
@8sp more typos on line 14 (URL of Instagram and medium)

https://github.com/8sp/8sp/blob/c37dbef8bcc1f663c6e4c5091041069ab951600b/README.md?plain=1#L14
